#ifndef MOONSWEEPERTYPEDEF_H
#define MOONSWEEPERTYPEDEF_H
#pragma once
#define IDM_OPTIONS 1

enum CHILD_WINDOW_ID {
	GAME_WINDOW_ID = 1,
	INFO_WINDOW_ID,
	SMILEY_WINDOW_ID
};

enum MOUSE_BUTTONS_STATE {
	LEFTCLICK,
	RIGHTCLICK,
	BOTH
};

#endif